name: unpub_aws
description: A collection of modules to use for deploying unpub into AWS infrastructure.
version: 0.1.0
homepage: https://github.com/bytedance/unpub
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  unpub: ^2.0.0
  minio: ^3.5.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  chunked_stream: ^1.4.1
  mockito: ^5.1.0
  build_runner: ^2.1.7
  path: ^1.8.1
  json_annotation: ^4.4.0
# dependency_overrides:
#   unpub:
#     path: ../unpub
