name: lint
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - run: cd unpub && dart pub get && dart analyze
      - run: dart format --set-exit-if-changed **/*.dart
